name       : haskell-fast-logger
version    : 2.4.10
release    : 1
source     :
    - http://hackage.haskell.org/package/fast-logger-2.4.10/fast-logger-2.4.10.tar.gz : dec4a5d1a88f822d08d334ee870a08a8bb63b2b226d145cd24a7f08676ce678d
license    : BSD-3-Clause
component  : programming.haskell
summary    : A fast logging system
description: |
    A fast logging system
builddeps  :
    - haskell-auto-update
    - haskell-cabal-install
    - haskell-easy-file
    - haskell-unix-time
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

