name       : haskell-fast-logger
version    : 2.4.11
release    : 2
source     :
    - https://hackage.haskell.org/package/fast-logger-2.4.11/fast-logger-2.4.11.tar.gz : bbe5deab58f435754dbe938cf0ddf26fc21f317c35fb3431d4bdb96809dea2a9
license    : BSD-3-Clause
component  : programming.haskell
summary    : A fast logging system
description: |
    A fast logging system
builddeps  :
    - haskell-auto-update
    - haskell-cabal-install
    - haskell-easy-file
    - haskell-text
    - haskell-unix-time
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

