name       : haskell-fast-logger
version    : 3.0.1
release    : 3
source     :
    - https://hackage.haskell.org/package/fast-logger-3.0.1/fast-logger-3.0.1.tar.gz : 45080ca54a3862ed22f78c2bcb56d023695c4f4fd37dbbac418248c07cdca53b
license    : BSD-3-Clause
component  : programming.haskell
summary    : A fast logging system
description: |
    A fast logging system
builddeps  :
    - haskell-auto-update-devel
    - haskell-cabal-install
    - haskell-easy-file-devel
    - haskell-unix-compat-devel
    - haskell-unix-time-devel
rundeps    :
    - devel:
        - haskell-auto-update-devel
        - haskell-easy-file-devel
        - haskell-unix-compat-devel
        - haskell-unix-time-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

